Replace `root` with `config_dir` and `data_dir`
rossmacarthur/sheldon pull request #112
Opened 2020-10-07 15:20 UTC by tapeinosyne

As briefly discussed in #110, it may be time to do away with the notion of a unified Sheldon root and define individual directories for data and configuration, which are a baseline requirement for the support of alternative directory layouts such as XDG .

As implemented, the change cannot be rightfully called a deprecation, as `root` is baldly scraped off the user interface:
  - `--root` causes commands to be refused.
  - `$SHELDON_ROOT` is silently ignored.
  - the `{{root}}` template variable offers a warning.

We may be happy with this, or we may opt for a more cautious approach and implement some simple deprecation mechanism for disused flags and environment variables.

It should be noted that the removal of `root` is not a breaking change for users who retained Sheldon's default directory configuration—a significant majority, I would expect.

2020-10-08 08:50 UTC, rossmacarthur requested changes

2020-10-09 12:58 UTC, tapeinosyne commented
(The branch will be cleaned up once the PR is ready to be merged.)

2020-10-12 12:57 UTC, rossmacarthur approved these changes
I'm happy with these changes, can we get them in soon?

2020-10-14 07:45 UTC, merged

2020-10-14 07:46 UTC, rossmacarthur commented
Thanks!